// Antiquities Card Data (March 1994)
// 100 cards total - expansion set, no basic lands

const ATQ_CARDS = {
  commons: [
    { name: "Amulet of Kroog" },
    { name: "Argivian Blacksmith" },
    { name: "Artifact Ward" },
    { name: "Circle of Protection: Artifacts" },
    { name: "Coral Helm" },
    { name: "Cursed Rack" },
    { name: "Damping Field" },
    { name: "Drafna's Restoration" },
    { name: "Dwarven Weaponsmith" },
    { name: "Energy Flux" },
    { name: "Goblin Artisans" },
    { name: "Grapeshot Catapult" },
    { name: "Haunting Wind" },
    { name: "Ivory Tower" },
    { name: "Jalum Tome" },
    { name: "Martyrs of Korlis" },
    { name: "Millstone" },
    { name: "Mishra's Factory" },
    { name: "Orcish Mechanics" },
    { name: "Ornithopter" },
    { name: "Powerleech" },
    { name: "Priest of Yawgmoth" },
    { name: "Primal Clay" },
    { name: "The Rack" },
    { name: "Sage of Lat-Nam" },
    { name: "Shapeshifter" },
    { name: "Shatterstorm" },
    { name: "Strip Mine" },
    { name: "Tablet of Epityr" },
    { name: "Tawnos's Wand" },
    { name: "Urza's Avenger" },
    { name: "Urza's Chalice" },
    { name: "Urza's Mine" },
    { name: "Urza's Power Plant" },
    { name: "Urza's Tower" },
    { name: "Wall of Spears" },
    { name: "Xenic Poltergeist" },
    { name: "Yawgmoth Demon" }
  ],
  uncommons: [
    { name: "Armageddon Clock" },
    { name: "Artifact Blast" },
    { name: "Ashnod's Altar" },
    { name: "Ashnod's Battle Gear" },
    { name: "Ashnod's Transmogrant" },
    { name: "Atog" },
    { name: "Bronze Tablet" },
    { name: "Clay Statue" },
    { name: "Clockwork Avian" },
    { name: "Colossus of Sardia" },
    { name: "Dragon Engine" },
    { name: "Feldon's Cane" },
    { name: "Gate to Phyrexia" },
    { name: "Golgothian Sylex" },
    { name: "Hurkyl's Recall" },
    { name: "Mightstone" },
    { name: "Onulet" },
    { name: "Phyrexian Gremlins" },
    { name: "Reconstruction" },
    { name: "Reverse Polarity" },
    { name: "Rocket Launcher" },
    { name: "Rukh Egg" },
    { name: "Staff of Zegon" },
    { name: "Su-Chi" },
    { name: "Tawnos's Coffin" },
    { name: "Tawnos's Weaponry" },
    { name: "Tetravus" },
    { name: "Titania's Song" },
    { name: "Transmute Artifact" },
    { name: "Triskelion" },
    { name: "Urza's Miter" },
    { name: "Weakstone" },
    { name: "Yotian Soldier" }
  ],
  rares: [
    { name: "Candelabra of Tawnos" },
    { name: "Citanul Druid" },
    { name: "Copy Artifact" },
    { name: "Crumble" },
    { name: "Detonate" },
    { name: "Gaea's Avenger" },
    { name: "Haunting Wind" },
    { name: "Mishra's War Machine" },
    { name: "Mishra's Workshop" },
    { name: "Phyrexian Gremlins" },
    { name: "Power Artifact" },
    { name: "Rakalite" },
    { name: "Sage of Lat-Nam" },
    { name: "Soul of Yawgmoth" },
    { name: "Tawnos's Coffin" },
    { name: "Tetravus" },
    { name: "Transmute Artifact" },
    { name: "Urza's Miter" }
  ],
  lands: [] // Antiquities has no basic lands - it's an expansion
};

// Add to SETS_CONFIG
SETS_CONFIG['atq'] = {
  fullName: "Antiquities",
  releaseDate: "March 1994",
  cardCount: 100,
  hasStarter: false,
  packSize: 8
};
